### DISCUSSION TITLE
Flussschaubild Kältekreis Vitotronic 200

### DISCUSSION THREAD

**Discussion by floh2307** [philippoo66/optolink-splitter#67] [Q&A]
Hallo zusammen,

hat zufällig diesen Kältekreis als Bild für die Home Assistant Integration nachgebaut?
![20241227_155749](https://github.com/user-attachments/assets/125eb6e7-6c46-474a-ba59-327ab6c4fb7b)
![20241227_141446](https://github.com/user-attachments/assets/40afc452-7a87-4a95-a099-f5dbf3201633)

**Comment by schnuller123** [comment]
kann mir mal einer erklären was die Symbole genau darstellen sollen
unteres Bild zB
Links ist die Heisse Seite 35,6° gehen rein und 36° gehen raus
Rechts = AussenEinheit Aussenluft = 8° und er saugt sich 1° raus?
zwischenwerte verstehe ich nicht!

**Reply by schnuller123** [reply]
sorry, hab schon erklärung gefunden
in einer Excel Liste mit den Datenpunkten

**Reply by floh2307** [reply]
Habs grade drunter gepostet

**Comment by floh2307** [comment]
![image](https://github.com/user-attachments/assets/28e4684f-618c-4b0f-9dc6-092c4a54a1d4)
![image](https://github.com/user-attachments/assets/95437436-3a29-4e0a-ba1a-514d49ea38c7)

**Reply by floh2307** [reply]
Hab mich inzwischen etwas weiter damit beschäftigt und es hinbekommen.
Sollte von jemand die roh Dateien benötigt werden, einfach melden.

![image](https://github.com/user-attachments/assets/439ebafd-3362-4267-aaad-5010b51f435b)

**Reply by thiemjoerg** [reply]
Hallo zusammen.
Sieht super aus. Aber ich frage mich, wie kann sich denn überhaupt auf der Vitotronic 200 diesen Kreis anzeigen lassen kann.
Ist das nur für bestimmte Modelle möglich? Ich habe eine Sole-WP Vitocal 300-G.
VG, Jörg

**Reply by FransOv** [reply]
In der Tab "WO1C Kaltekreis" in https://github.com/user-attachments/files/18600707/Viessmann.Parameter.Adresses.xlsx sind die datenpunkte der Kaltekreis von Vitocal 300-G. Meine Poll Liste ist hier: https://github.com/philippoo66/optolink-splitter/wiki/350-Poll-Configuration-Samples#vitocal-300-g-bwc-301c16-of-fransov. Damit hab ich in Home Assistant diese Darstellung gemacht:
![image](https://github.com/user-attachments/assets/4c5eb5ff-c35e-4bed-b3c2-5e476f633332)

**Reply by thiemjoerg** [reply]
Hallo @FransOv. Das seht auch super aus. Ich verwende allerdings iobroker mit HabPanel und kein Home Assistant.
Ich wüsste jetzt nicht, wie ich das in iobroker umsetzen kann.

Meine Frage war, we man sich das in dem Display der Vitotronic 200 anzeigen kann, wie ganz oben in den Fotos.

VG, Jörg

**Reply by FransOv** [reply]
Ich Kenne ioBroker nicht. In HA ist es ein Picture elements card, dass ist eine Abbildung mit darüber die Werte der Datenpunkte geschrieben.

**Reply by floh2307** [reply]
Hallo @thiemjoerg,
du kannst das Anlagenschaubild in der Codierebene 1 anzeigen lassen.
Dann kommst du auf genau das Bild

**Reply by thiemjoerg** [reply]
Hallo @floh2307 .
Könntest du mir noch sagen, wie ich in die Codierebene 1 gelange. Das sagt mir leider nichts.
Vielen Dank und VG

**Reply by floh2307** [reply]
![image](https://github.com/user-attachments/assets/307e4f8a-485b-4f8c-a740-f91941274a50)

**Reply by thiemjoerg** [reply]
Super, vielen Dank. Das probiere ich gleich mal aus.

**Reply by CaneTLOTW** [reply]
> Hab mich inzwischen etwas weiter damit beschäftigt und es hinbekommen. Sollte von jemand die roh Dateien benötigt werden, einfach melden.
> 
Hi @floh2307 ich würde etwas vergleichbares gerne für meine 222-S nachbauen. Kannst du mir deine "Vorlage" zur Verfügung stellen?

**Reply by floh2307** [reply]
@CaneTLOTW : Was brauchst du alles? 
Nur dien Grafik?

**Reply by CaneTLOTW** [reply]
Möglichst alles was sich aus HA kopieren lässt ;)
Gerne auch den YAML code.

**Reply by materoxxx** [reply]
Can I have it too? thank you

**Comment by FransOv** [comment]
Das Bild im Excel ist von eine Sole Wärmepumpe. Im  Vitotronic Serviceanleitung sind die Bilder andere Typen.

**Comment by philippoo66** [comment]
@floh2307 darf ich das Bild in's Readme übernehmen?

**Comment by floh2307** [comment]
@philippoo66 klar kannst du machen

**Comment by materoxxx** [comment]
where can I find the template or the images for home assistant? Thank you

**Comment by FransOv** [comment]
Info about Home Assistant integration can be found in the wiki: https://github.com/philippoo66/optolink-splitter/wiki/210-Home-Assistant-Integration-of-Optolink%E2%80%90Splitter

**Reply by materoxxx** [reply]
Thank you but I meant the actual pictures to use in home assistant or the code to create the card like in the example. I integrated  the entities already into home assistant, I was just looking to seeing them "nice" with the picture card

**Reply by FransOv** [reply]
Sorry, misunderstood your question. Mine is for a ground source heatpump so that would not be applicable for you.
![Screenshot_20250921_162240_Home Assistant](https://github.com/user-attachments/assets/8961b097-30f3-4e16-aef6-5d0b4d009045)

**Reply by materoxxx** [reply]
Thanks anyways

**Comment by floh2307** [comment]
@materoxxx @CaneTLOTW 
Sorry for the late response.
Here the pictures:
![Kaeltekreis_leer](https://github.com/user-attachments/assets/006f1ab6-50b6-4ff3-b9d7-c09f6b4268a9)
![Übersicht_leer](https://github.com/user-attachments/assets/e6f9e64f-52d7-4078-9e14-7011d0778bcc)

```
type: picture-elements
elements:
  - type: state-label
    entity: sensor.wpr3_split_k71_ofanactualspeed_0x1a71
    style:
      left: 32%
      top: 78%
      color: white
  - type: state-label
    style:
      left: 95%
      top: 78%
      color: white
    entity: sensor.wpr3_split_k54_current_compressor_frequency_0x1a54
  - type: state-icon
    entity: binary_sensor.wp_verdichter_status
    style:
      left: 83%
      top: 78%
  - type: state-icon
    entity: binary_sensor.brennerstatus
    style:
      left: 76%
      top: 44.5%
  - type: state-label
    style:
      left: 76%
      top: 53%
      color: white
    entity: sensor.modulation
  - type: state-label
    style:
      left: 84%
      top: 70%
      color: white
    entity: sensor.wpr3_sekundar_vl_0xb402
  - type: state-label
    entity: sensor.vcaldens_gemeinsame_vorlauftemperatur_0x01f7
    style:
      left: 93%
      top: 35%
      color: white
  - type: state-label
    style:
      left: 76%
      top: 35%
      color: white
    entity: sensor.vcaldens_kesseltemperatur_0xb370
  - type: state-label
    entity: sensor.wpr3_sekundar_rl_0xb403
    style:
      left: 51%
      top: 56%
      color: white
  - type: state-label
    entity: sensor.wpr3_b421_drehzahl_sekundaerpumpe_0xb42
    style:
      left: 51%
      top: 50%
      color: white
  - type: state-label
    entity: sensor.wpr3_aussentemperatur_0x01c1
    style:
      left: 10%
      top: 77.5%
      color: white
  - type: state-label
    entity: sensor.wpr3_b422_drehzahl_ww_pumpe_0xb422
    style:
      left: 41%
      top: 35%
      color: white
  - type: state-label
    entity: sensor.wpr3_ww_temperatur_oben_0x01cd
    style:
      left: 35%
      top: 50%
      color: white
  - type: state-label
    entity: sensor.wpr3_ww_temperatur_ausgang_0x01d0
    style:
      left: 20%
      top: 30%
      color: white
  - type: state-icon
    entity: binary_sensor.wpr_wo1h_gueltbetriebsmodusww_0x1185
    style:
      left: 33%
      top: 36%
  - type: state-icon
    entity: binary_sensor.wpr_relaisstatus_3w_ventilheizen_ww1_0x0494
    style:
      left: 41%
      top: 41%
    icon: mdi:pump
    state_color: true
  - type: state-label
    style:
      left: 10%
      top: 50%
      color: white
    entity: sensor.vcaldens_bivalenztemperatur_wp_0xb380
  - type: state-label
    style:
      left: 10%
      top: 56%
      color: white
    entity: sensor.vcaldens_bivalenztemperatur_gwg_0xb381
  - type: state-icon
    entity: binary_sensor.wpr_relaisstatus_sekpumpe1_0x0484
    style:
      left: 59.5%
      top: 49%
  - type: state-icon
    entity: sensor.wpr3_split_k71_ofanactualspeed_0x1a71
    style:
      left: 45%
      top: 78%
    icon: mdi:fan
  - type: state-label
    entity: number.wpr_ww_temp_soll1_0x6000
    style:
      left: 79%
      top: 19%
      color: white
  - type: state-icon
    entity: binary_sensor.wpr3_geraetestatus_frostschutz_hk1_0x1410
    style:
      left: 46%
      top: 5.5%
  - type: state-icon
    entity: binary_sensor.wpr3_sammelstoerung_0x0491
    style:
      left: 55%
      top: 5.5%
      color: red
  - type: state-label
    entity: sensor.hk_raumsolltemperatur_0xa406
    style:
      left: 93%
      top: 5.5%
      color: white
  - type: state-icon
    style:
      left: 80%
      top: 5.5%
    entity: climate.wpr_wo1h_hk1_betriebsart1_0xb000
grid_options:
  rows: 5
  columns: 12
image: /api/image/serve/f1c51a1fcfd1e7bb3b8a88c2d4c1fc49/512x512
```
```
type: picture-elements
elements:
  - type: state-label
    entity: sensor.wpr3_split_k71_ofanactualspeed_0x1a71
    style:
      left: 90%
      top: 45%
      color: white
  - type: state-label
    entity: sensor.wpr3_split_oat_ats_0x01e6
    style:
      left: 85%
      top: 30%
      color: white
  - type: state-label
    style:
      left: 85%
      top: 60%
      color: white
    entity: sensor.wpr3_split_omt_verdampfertemperatur_0x01e7
  - type: state-label
    style:
      left: 50%
      top: 30%
      color: white
    entity: sensor.wpr3_split_k54_current_compressor_frequency_0x1a54
  - type: state-label
    style:
      left: 50%
      top: 75%
      color: white
    entity: sensor.wpr3_split_k55_eev_motor_position_0x1a55
  - type: state-label
    style:
      left: 65%
      top: 75%
      color: white
    entity: sensor.wpr3_split_oct_verdampfervorlauftemp_0x01e8
  - type: state-label
    style:
      left: 35%
      top: 75%
      color: white
    entity: sensor.wpr3_split_irt_kondensator_rl_0x01eb
  - type: state-label
    style:
      left: 15%
      top: 75%
      color: white
    entity: sensor.wpr3_sekundar_rl_0xb403
  - type: state-label
    style:
      left: 15%
      top: 30%
      color: white
    entity: sensor.wpr3_sekundar_vl_0xb402
  - type: state-label
    entity: sensor.wpr3_b422_drehzahl_ww_pumpe_0xb422
    style:
      left: 45%
      top: 17%
      color: white
  - type: state-label
    entity: sensor.wpr3_b421_drehzahl_sekundaerpumpe_0xb42
    style:
      left: 15%
      top: 17%
      color: white
  - type: state-icon
    entity: binary_sensor.wpr_relaisstatus_3w_ventilheizen_ww1_0x0494
    style:
      left: 36%
      top: 17%
    icon: mdi:pump
  - type: state-icon
    entity: binary_sensor.wpr_relaisstatus_sekpumpe1_0x0484
    style:
      left: 6%
      top: 17%
    state_color: true
  - type: state-icon
    entity: binary_sensor.wp_verdichter_status
    style:
      left: 49.7%
      top: 39%
  - type: state-label
    entity: sensor.wpr3_aussentemperatur_0x01c1
    style:
      left: 69%
      top: 6.5%
      color: white
  - type: state-icon
    entity: binary_sensor.wpr3_geraetestatus_frostschutz_hk1_0x1410
    style:
      left: 78%
      top: 6.5%
      color: white
  - type: state-icon
    entity: binary_sensor.wpr3_sammelstoerung_0x0491
    style:
      left: 50%
      top: 6.5%
      color: red
  - type: state-icon
    style:
      left: 30%
      top: 17%
    entity: binary_sensor.wpr_wo1h_gueltbetriebsmodusww_0x1185
  - type: state-label
    entity: sensor.wp_protection_reason
    style:
      left: 50%
      top: 50%
      color: white
  - type: state-label
    entity: sensor.wp_cop
    style:
      left: 50%
      top: 90%
      color: white
    prefix: "COP "
grid_options:
  rows: 5
  columns: 12
image: /api/image/serve/d4909d0f7a33f76190e64a455ec3193c/512x512
´´´
